CREATE TABLE products (
    id UUID PRIMARY KEY,
    sku VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    short_description VARCHAR(500) NOT NULL,
    full_description TEXT,
    sale_price DECIMAL(19, 4) NOT NULL,
    cost_price DECIMAL(19, 4) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'BRL',
    status VARCHAR(50) NOT NULL,
    supplier_sku VARCHAR(100),
    supplier_name VARCHAR(255),
    supplier_product_url VARCHAR(1000),
    lead_time_days INTEGER,
    is_dropship BOOLEAN NOT NULL DEFAULT true,
    weight DECIMAL(10, 4),
    length DECIMAL(10, 4),
    width DECIMAL(10, 4),
    height DECIMAL(10, 4),
    slug VARCHAR(255) NOT NULL,
    category_id UUID,
    brand VARCHAR(255),
    meta_title VARCHAR(255),
    meta_description VARCHAR(500),
    compare_at_price DECIMAL(19, 4),
    stock_quantity INTEGER,
    tags TEXT,
    attributes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_products_sku UNIQUE (sku),
    CONSTRAINT uk_products_slug UNIQUE (slug)
);
